base_model: NousResearch/Meta-Llama-3.1-8B

load_in_8bit: false
load_in_4bit: true

datasets:
  - path: ./data/training_data_before_2025.jsonl
    type: completion
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./outputs/qlora-finetuned

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true

wandb_project: llama-ec2
wandb_entity: duc-ph-san-jose-state-university
wandb_watch: all
wandb_name: llama-8b-test-run
wandb_log_model: end

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 4
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.00001

bf16: auto
tf32: false

  # gradient_checkpointing: true
  # gradient_checkpointing_kwargs:
  #   use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 10
evals_per_epoch: 1
saves_per_epoch: 1
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_activation_checkpointing: true

special_tokens:
  pad_token: "<|eot_id|>"